name: check-build

on:
  pull_request:
    types: [opened, reopened]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: install packages
        run: pnpm install

      - name: check build files
        run: pnpm run build && git diff --exit-code
